from __future__ import annotations

"""Fuellmaterial (Rauschen) fuer den Abruf-Pruefstand, absichtlich KEINE
gueltige Antwort auf die Messaufgaben."""

import sys as _sys
from pathlib import Path as _Path

# Findet die Repo-Wurzel an schema.sql statt an einer Anzahl von Ebenen.
# Eine feste Ebenenzahl (parent.parent) bricht beim naechsten Umzug lautlos;
# ein Merkmal der Wurzel bricht nie. Danach liegen Wurzel und die beiden
# Ordner mit importierbaren Modulen im Suchpfad.
_w = _Path(__file__).resolve().parent
while not (_w / "schema.sql").exists() and _w != _w.parent:
    _w = _w.parent
_sys.path[:0] = [str(_w)] + [str(_w / o) for o in
                 ("kern", "haken", "schreibpruefstand", "melder", "migrationen")]

FUELL_KNOTEN: list[dict] = [
    # verbrauchsabrechnung
    {"abteilung": "verbrauchsabrechnung", "slug": "jahresabrechnung-terminplan",
     "title": "Terminplan Jahresabrechnung", "summary": "Der Rechnungslauf fuer die Jahresabrechnung folgt einem festen Kalender, damit alle Tarifgruppen gleichmaessig verteilt bearbeitet werden koennen.",
     "content": "Fuer jede Tarifgruppe ist ein Zeitfenster hinterlegt, in dem die Abrechnungsdaten aus dem Lastgangsystem gezogen und geprueft werden. Verschiebt sich ein Fenster, wird die Folgegruppe automatisch nachgezogen, um Leerlauf im Rechnungslauf zu vermeiden. Das Team gleicht den Plan monatlich mit dem Messstellenbetreiber ab."},
    {"abteilung": "verbrauchsabrechnung", "slug": "tarifwechsel-freigabefenster",
     "title": "Freigabefenster fuer Tarifwechsel", "summary": "Ein Tarifwechsel wird nur innerhalb definierter Freigabefenster in das Abrechnungssystem uebernommen, um doppelte Buchungen zu vermeiden.",
     "content": "Ausserhalb der Fenster gestellte Wechselwuensche landen in einer Warteliste und werden zum naechsten Termin nachgezogen. Die Kollegin im Backoffice prueft vorab, ob der neue Tarif zur Verbrauchsklasse der Kd-Nr. passt. Erst nach dieser Pruefung wird der Wechsel technisch scharfgestellt."},
    {"abteilung": "verbrauchsabrechnung", "slug": "verbrauchsprognose-heizperiode",
     "title": "Verbrauchsprognose zur Heizperiode", "summary": "Vor Beginn der Heizperiode wird ein Prognosemodell auf Basis der Vorjahreswerte und der Wetterdaten neu kalibriert.",
     "content": "Das Modell schaetzt den erwarteten Jahresverbrauch je Kd-Nr. und dient als Grundlage fuer die Abschlagsberechnung. Weicht die Prognose deutlich vom bisherigen Verlauf ab, wird ein manueller Blick auf die Verbrauchsklasse empfohlen. Die Kalibrierung laeuft einmal jaehrlich vor Oktober."},
    {"abteilung": "verbrauchsabrechnung", "slug": "zaehlerplatz-normgroesse",
     "title": "Normgroesse fuer neue Zaehlerplaetze", "summary": "Bei Neubauten muss der Zaehlerplatz die aktuelle Normgroesse einhalten, sonst verweigert die Abnahme die Freigabe.",
     "content": "Die Abteilung prueft Bauplaene vorab gegen eine Checkliste mit Mindestmassen und Zugaenglichkeit. Fehlt ein Freiraum fuer Wartungsarbeiten, wird die Planung an den Bautraeger zurueckgespielt. Erst nach bestandener Pruefung wird der Zaehlerplatz fuer den Anschluss freigegeben."},
    {"abteilung": "verbrauchsabrechnung", "slug": "abrechnungsperiode-schaltjahr",
     "title": "Schaltjahr in der Abrechnungsperiode", "summary": "In Schaltjahren muss die Tageszahl der Abrechnungsperiode korrekt beruecksichtigt werden, sonst entstehen kleine Abweichungen im Abschlagsplan.",
     "content": "Das Abrechnungssystem rechnet die Periode standardmaessig mit 365 Tagen, was im Schaltjahr eine Korrektur erfordert. Die Fachabteilung pflegt dafuer einen jaehrlichen Hinweis in den Rechnungslauf-Unterlagen ein. Ohne die Korrektur verschieben sich Abschlagstermine minimal, was in der Jahresuebersicht auffaellt."},
    {"abteilung": "verbrauchsabrechnung", "slug": "lastgangdaten-uebermittlung",
     "title": "Uebermittlung von Lastgangdaten", "summary": "Lastgangdaten werden taeglich vom Messstellenbetreiber uebertragen und vor der Weiterverarbeitung auf Vollstaendigkeit geprueft.",
     "content": "Fehlt ein Uebertragungsblock, wird automatisch eine Nachforderung an den Messstellenbetreiber ausgeloest. Erst wenn alle Blocke vollstaendig vorliegen, fliessen die Daten in die Verbrauchsauswertung ein. Die Pruefung laeuft als taeglicher Stapeljob in der Nacht."},
    {"abteilung": "verbrauchsabrechnung", "slug": "verbrauchsabweichung-plausibilitaet",
     "title": "Plausibilitaetspruefung bei Verbrauchsabweichung", "summary": "Weicht der gemessene Verbrauch stark vom Vorjahreswert ab, prueft eine automatische Plausibilitaetsregel den Fall vor der Weiterverarbeitung.",
     "content": "Die Regel vergleicht den aktuellen Wert mit dem Verlauf der letzten drei Perioden und markiert Ausreisser fuer eine manuelle Sichtung. Ursachen koennen ein geaenderter Haushalt, ein neues Geraet oder eine geaenderte Nutzung sein. Die Sichtung erfolgt durch eine Kollegin aus der Fachabteilung."},
    {"abteilung": "verbrauchsabrechnung", "slug": "rechnungslauf-stapelverarbeitung",
     "title": "Stapelverarbeitung im Rechnungslauf", "summary": "Der Rechnungslauf verarbeitet Kundengruppen in Stapeln, um die Systemlast auf mehrere Nachtfenster zu verteilen.",
     "content": "Jeder Stapel enthaelt eine feste Anzahl an Kd-Nr. und wird nacheinander an das Abrechnungssystem uebergeben. Bricht ein Stapel ab, wird nur dieser Teil erneut angestossen, ohne die uebrigen Stapel zu beruehren. Die Planung der Stapelgroessen wird vierteljaehrlich an das Kundenwachstum angepasst."},
    # netzbetrieb
    {"abteilung": "netzbetrieb", "slug": "netzanschluss-neubaugebiet",
     "title": "Netzanschluss fuer ein Neubaugebiet", "summary": "Fuer neue Baugebiete wird der Netzanschluss in Abstimmung mit der Gemeinde und dem Tiefbau geplant, bevor die ersten Grundstuecke bebaut werden.",
     "content": "Die Planung beruecksichtigt die voraussichtliche Anzahl der Anschluesse und die zukuenftige Lastentwicklung im Gebiet. Ein Abstimmungstermin mit der Gemeinde klaert die Trassenfuehrung entlang der geplanten Strassen. Erst nach dieser Abstimmung beginnt die eigentliche Ausschreibung der Bauleistung."},
    {"abteilung": "netzbetrieb", "slug": "baustellenkoordination-tiefbau",
     "title": "Koordination von Tiefbaustellen", "summary": "Mehrere Tiefbaustellen im selben Strassenzug werden zeitlich koordiniert, damit Anwohner nicht mehrfach von Sperrungen betroffen sind.",
     "content": "Die Koordination laeuft ueber einen gemeinsamen Baustellenkalender mit anderen Leitungstraegern wie Wasser und Telekommunikation. Ueberschneiden sich zwei Vorhaben, wird ein gemeinsamer Graben verhandelt, um Kosten und Aufwand zu senken. Der Bereitschaftsdienst wird ueber jede aktive Baustelle informiert."},
    {"abteilung": "netzbetrieb", "slug": "erdgas-odorierung-kontrolle",
     "title": "Kontrolle der Erdgas-Odorierung", "summary": "Die Odorierung des Erdgases wird regelmaessig kontrolliert, damit Lecks im Netz durch den charakteristischen Geruch fruehzeitig auffallen.",
     "content": "An festgelegten Messpunkten im Netz wird die Odorstoffkonzentration stichprobenartig gepruft und protokolliert. Liegt ein Wert ausserhalb der Toleranz, wird die Dosierung an der Einspeisestelle nachjustiert. Die Kontrolle ist Teil der regelmaessigen Netzueberwachung."},
    {"abteilung": "netzbetrieb", "slug": "strassenbeleuchtung-ausfallmeldung",
     "title": "Ausfallmeldung Strassenbeleuchtung", "summary": "Ausfaelle einzelner Strassenlaternen werden ueber ein Meldeportal erfasst und nach Dringlichkeit in die Instandhaltung eingeplant.",
     "content": "Buerger und Gemeinde koennen Ausfaelle direkt online melden, die Meldung wird automatisch geokodiert. Haeufen sich Meldungen in einem Strassenzug, wird eine gemeinsame Reparaturfahrt geplant statt einzelner Anfahrten. Die Bearbeitungszeit richtet sich nach der Verkehrsbedeutung der Strasse."},
    {"abteilung": "netzbetrieb", "slug": "ladesaeule-inbetriebnahme",
     "title": "Inbetriebnahme einer neuen Ladesaeule", "summary": "Vor der Inbetriebnahme einer Ladesaeule wird die Netzverstaerkung am Standort geprueft, damit Spitzenlasten sicher abgedeckt sind.",
     "content": "Der Netzbetrieb simuliert die zu erwartende Gleichzeitigkeit mehrerer Ladevorgaenge am Standort. Reicht die vorhandene Kapazitaet nicht aus, wird ein zusaetzlicher Leitungsabschnitt eingeplant. Erst nach bestandener Abnahmepruefung wird die Saeule fuer die Oeffentlichkeit freigeschaltet."},
    {"abteilung": "netzbetrieb", "slug": "stoerungsmeldung-prioritaeten",
     "title": "Prioritaeten bei Stoerungsmeldungen", "summary": "Eingehende Stoerungsmeldungen werden nach Ausmass und betroffener Infrastruktur priorisiert, bevor der Bereitschaftsdienst ausrueckt.",
     "content": "Eine grossflaechige Versorgungsunterbrechung hat immer Vorrang vor einer Einzelmeldung. Die Priorisierung erfolgt automatisiert anhand der Anzahl betroffener Anschluesse und wird von der Leitstelle gegengeprueft. Der Bereitschaftsdienst erhaelt die Reihenfolge direkt auf das Diensthandy."},
    {"abteilung": "netzbetrieb", "slug": "winterdienst-netzzufahrten",
     "title": "Winterdienst fuer Netzzufahrten", "summary": "Zufahrten zu wichtigen Netzanlagen werden im Winterdienst priorisiert geraeumt, damit ein Einsatzfahrzeug im Stoerfall jederzeit durchkommt.",
     "content": "Eine Liste kritischer Standorte wird vor der Wintersaison mit dem Fuhrpark abgestimmt und an den Raeumdienst uebergeben. Bei starkem Schneefall wird die Liste taeglich neu priorisiert. Die Abstimmung verhindert, dass ein Einsatzfahrzeug bei einer Stoerung im Schnee steckenbleibt."},
    {"abteilung": "netzbetrieb", "slug": "fuhrpark-einsatzplanung",
     "title": "Einsatzplanung im Fuhrpark", "summary": "Die Fahrzeuge des Fuhrparks werden je nach Einsatzart und Ausstattung fuer Bau- und Stoerungseinsaetze eingeplant.",
     "content": "Ein zentrales Buchungssystem zeigt, welches Fahrzeug fuer welchen Einsatztyp verfuegbar ist und wann die naechste Pruefung ansteht. Ueberschneiden sich zwei Einsaetze, entscheidet die Dringlichkeit der Stoerungsmeldung ueber die Zuteilung. Der Fuhrpark wird monatlich auf Auslastung ausgewertet."},
    # kundenservice
    {"abteilung": "kundenservice", "slug": "callcenter-erreichbarkeitsquote",
     "title": "Erreichbarkeitsquote im Callcenter", "summary": "Die Erreichbarkeitsquote des Callcenters wird woechentlich ausgewertet, um Personalbedarf und Spitzenzeiten besser einzuplanen.",
     "content": "Liegt die Quote unter dem internen Zielwert, wird geprueft, ob zusaetzliche Kollegen in der Spitzenzeit eingeplant werden koennen. Die Auswertung unterscheidet zwischen allgemeinen Anfragen und technischen Stoerungsmeldungen. Ergebnisse fliessen in die naechste Dienstplanrunde ein."},
    {"abteilung": "kundenservice", "slug": "terminfenster-vor-ort-termine",
     "title": "Terminfenster fuer Vor-Ort-Termine", "summary": "Vor-Ort-Termine werden in festen Zeitfenstern angeboten, damit Techniker und Kunden planbar aufeinandertreffen.",
     "content": "Ein Kunde waehlt online eines von mehreren Fenstern, das System gleicht die Verfuegbarkeit der Technikerteams automatisch ab. Wird ein Termin kurzfristig storniert, ruecken wartende Anfragen automatisch nach. Die Fensterbreite wurde nach Kundenrueckmeldung von vier auf zwei Stunden verkuerzt."},
    {"abteilung": "kundenservice", "slug": "beschwerdequote-monatsreport",
     "title": "Beschwerdequote im Monatsreport", "summary": "Die monatliche Beschwerdequote wird nach Themenfeld ausgewertet, um wiederkehrende Ursachen im Kundenservice zu erkennen.",
     "content": "Jede Beschwerde wird bei Eingang kategorisiert, etwa nach Erreichbarkeit, Wartezeit oder Informationsstand. Haeuft sich ein Thema, wird es an die zustaendige Fachabteilung zur Ursachenklaerung weitergegeben. Der Report geht monatlich an die Teamleitung des Kundenservice."},
    {"abteilung": "kundenservice", "slug": "kundenportal-self-service",
     "title": "Self-Service im Kundenportal", "summary": "Das Kundenportal bietet einen Self-Service-Bereich, in dem Kunden Stammdaten und Verbrauchsuebersichten selbst einsehen koennen.",
     "content": "Ziel ist es, einfache Anliegen aus der Telefonwarteschlange herauszuhalten und direkt online loesbar zu machen. Die Nutzungszahlen werden regelmaessig ausgewertet, um weitere Funktionen im Portal zu priorisieren. Ein verstaendlicher Aufbau der Menuepunkte wird dabei besonders beruecksichtigt."},
    {"abteilung": "kundenservice", "slug": "warteschleifenansage-aktualisierung",
     "title": "Aktualisierung der Warteschleifenansage", "summary": "Die Ansage in der Telefonwarteschlange wird bei laengeren Wartezeiten oder besonderen Ereignissen kurzfristig angepasst.",
     "content": "Bei einer grossflaechigen Stoerung wird zuerst ein Hinweistext in die Ansage eingespielt, bevor der Anrufer mit einem Mitarbeiter verbunden wird. Das entlastet die Leitungen, weil viele Anliegen dadurch bereits vorab beantwortet sind. Die Aenderung wird von einer Kollegin im Kundenservice freigegeben."},
    {"abteilung": "kundenservice", "slug": "rueckrufmanagement-spitzenzeiten",
     "title": "Rueckrufmanagement in Spitzenzeiten", "summary": "Bei hohem Anrufaufkommen bietet das System einen Rueckruf statt einer langen Wartezeit an, um die Warteschlange zu entlasten.",
     "content": "Der Kunde hinterlaesst eine Nummer und wird in der Reihenfolge des Eingangs zurueckgerufen, sobald ein Platz frei ist. Die durchschnittliche Rueckrufzeit wird taeglich beobachtet und bei Abweichung an die Teamleitung gemeldet. Die Funktion wurde vor allem fuer Stoerungsspitzen eingefuehrt."},
    {"abteilung": "kundenservice", "slug": "mehrsprachige-hotline-pilot",
     "title": "Pilotprojekt mehrsprachige Hotline", "summary": "In einem Pilotprojekt wird eine zusaetzliche Sprachoption fuer die Kundenhotline getestet, um mehr Anliegen direkt zu klaeren.",
     "content": "Zunaechst wird die Option nur zu bestimmten Tageszeiten angeboten und die Nutzung ausgewertet. Steigt die Nachfrage deutlich, wird eine dauerhafte Erweiterung des Angebots geprueft. Rueckmeldungen der Anrufer fliessen direkt in die Bewertung des Pilotprojekts ein."},
    {"abteilung": "kundenservice", "slug": "kundenzufriedenheit-nachbefragung",
     "title": "Nachbefragung zur Kundenzufriedenheit", "summary": "Nach einem abgeschlossenen Vor-Ort-Termin erhaelt der Kunde eine kurze Nachbefragung zur Zufriedenheit mit dem Ablauf.",
     "content": "Die Befragung umfasst wenige Fragen zu Puenktlichkeit, Freundlichkeit und Verstaendlichkeit der Erklaerung. Die Ergebnisse werden je Team ausgewertet und in der naechsten Teambesprechung besprochen. Eine niedrige Bewertung wird von der Teamleitung einzeln nachverfolgt."},
    # personal
    {"abteilung": "personal", "slug": "dienstplan-schichtwechsel",
     "title": "Schichtwechsel im Dienstplan", "summary": "Beim Schichtwechsel wird eine kurze Uebergabe dokumentiert, damit offene Vorgaenge nicht zwischen zwei Schichten verlorengehen.",
     "content": "Die Uebergabe umfasst laufende Stoerungen, offene Kundenanliegen und Besonderheiten des Tages. Sie wird in einem gemeinsamen Uebergabeprotokoll festgehalten, das beide Schichten einsehen koennen. Fehlt die Uebergabe, wird dies in der naechsten Teambesprechung angesprochen."},
    {"abteilung": "personal", "slug": "schulungsnachweis-pflichttermine",
     "title": "Nachweis fuer Pflichtschulungen", "summary": "Pflichtschulungen muessen innerhalb einer festen Frist absolviert und der Nachweis in der Personalakte hinterlegt werden.",
     "content": "Eine automatische Erinnerung informiert die Kollegin oder den Kollegen rechtzeitig vor Ablauf der Frist. Fehlt der Nachweis weiterhin, wird die Fuehrungskraft ueber den offenen Termin informiert. Die Uebersicht der Fristen wird zentral von der Personalabteilung gepflegt."},
    {"abteilung": "personal", "slug": "arbeitsschutzunterweisung-jaehrlich",
     "title": "Jaehrliche Arbeitsschutzunterweisung", "summary": "Alle Mitarbeitenden im Aussendienst durchlaufen jaehrlich eine Arbeitsschutzunterweisung zu den aktuellen Gefahrenschwerpunkten.",
     "content": "Die Inhalte werden vor jeder Runde an neue Vorkommnisse und veraenderte Arbeitsmittel angepasst. Die Teilnahme wird in einer Liste erfasst und von der Personalabteilung nachgehalten. Wer die Unterweisung verpasst, erhaelt zeitnah einen Ersatztermin."},
    {"abteilung": "personal", "slug": "arbeitszeitkonto-ausgleich",
     "title": "Ausgleich des Arbeitszeitkontos", "summary": "Ueberstunden auf dem Arbeitszeitkonto werden nach einem festen Rhythmus mit der Fuehrungskraft besprochen und ausgeglichen.",
     "content": "Ziel ist ein moeglichst ausgeglichener Kontostand am Jahresende, um Uebertraege gering zu halten. Bei deutlich steigenden Stunden wird gemeinsam nach einer Entlastung im Team gesucht. Die Auswertung erfolgt quartalsweise durch die Personalabteilung."},
    {"abteilung": "personal", "slug": "bereitschaftsdienst-rotation",
     "title": "Rotation im Bereitschaftsdienst", "summary": "Der Bereitschaftsdienst rotiert nach einem festen Turnus durch das Team, damit die Belastung gleichmaessig verteilt bleibt.",
     "content": "Die Rotation beruecksichtigt vorherige Bereitschaftswochen, damit niemand ueberdurchschnittlich oft eingeteilt wird. Aenderungen im Turnus werden rechtzeitig im Team bekanntgegeben. Der Bereitschaftsdienst erhaelt zur Vorbereitung eine kurze Einweisung in aktuelle Netzbesonderheiten."},
    {"abteilung": "personal", "slug": "neueinstellung-einarbeitung",
     "title": "Einarbeitung neuer Kolleginnen und Kollegen", "summary": "Neue Mitarbeitende durchlaufen einen strukturierten Einarbeitungsplan mit festen Ansprechpersonen in den ersten Wochen.",
     "content": "Der Plan sieht wechselnde Stationen in verschiedenen Teams vor, damit die Zusammenhaenge zwischen den Abteilungen verstaendlich werden. Am Ende jeder Station gibt es ein kurzes Feedbackgespraech. Offene Fragen werden gesammelt und am Ende der Einarbeitung gemeinsam besprochen."},
    {"abteilung": "personal", "slug": "gesundheitstag-teilnahme",
     "title": "Teilnahme am Gesundheitstag", "summary": "Der jaehrliche Gesundheitstag bietet freiwillige Angebote wie Rueckenschulung und Sehtest fuer alle Mitarbeitenden an.",
     "content": "Die Teilnahme ist freiwillig und wird nicht auf die Arbeitszeit angerechnet, sofern sie ausserhalb der Kernarbeitszeit stattfindet. Ruecklauf und Interesse werden nach dem Tag ausgewertet, um das Angebot im Folgejahr anzupassen. Die Organisation liegt bei der Personalabteilung."},
    {"abteilung": "personal", "slug": "teamsitzung-protokollpflicht",
     "title": "Protokollpflicht bei Teamsitzungen", "summary": "Jede regelmaessige Teamsitzung wird protokolliert, damit Beschluesse auch fuer nicht anwesende Kolleginnen nachvollziehbar bleiben.",
     "content": "Das Protokoll haelt Beschluesse, offene Punkte und Zustaendigkeiten in kurzer Form fest. Es wird zeitnah im gemeinsamen Ablageordner hinterlegt und beim naechsten Termin kurz nachgehalten. Fehlende Punkte werden auf die naechste Sitzung uebertragen."},
    # openlehr-privat
    {"abteilung": "openlehr-privat", "slug": "openlehr-testabdeckung-luecken",
     "title": "Luecken in der Testabdeckung", "summary": "Eine Auswertung der Testabdeckung in der openlehr-App zeigt, welche Module noch ohne automatisierte Pruefung sind.",
     "content": "Besonders bei neu hinzugefuegten Bildschirmen fehlt oft noch ein begleitender Test. Die Auswertung dient als Grundlage, um die naechsten Testfaelle zu priorisieren statt beliebig zu ergaenzen. Module mit Nutzereingaben werden dabei bevorzugt behandelt."},
    {"abteilung": "openlehr-privat", "slug": "openlehr-oberflaechenbeschriftung-konsistenz",
     "title": "Konsistenz der Oberflaechenbeschriftung", "summary": "Beschriftungen in der openlehr-App werden auf einheitliche Begriffe geprueft, damit gleiche Funktionen ueberall gleich benannt sind.",
     "content": "Eine Liste haeufig verwendeter Begriffe dient als Nachschlagewerk beim Anlegen neuer Bildschirme. Weicht eine Beschriftung ohne Grund vom Standardbegriff ab, wird sie vor der Auslieferung vereinheitlicht. Ziel ist, dass Nutzer keine unterschiedlichen Woerter fuer dieselbe Handlung lernen muessen."},
    {"abteilung": "openlehr-privat", "slug": "openlehr-app-auslieferung-testflight",
     "title": "Auslieferung ueber Testflight", "summary": "Neue Versionen der openlehr-App werden zunaechst ueber Testflight an eine kleine Gruppe ausgeliefert, bevor eine breitere Freigabe erfolgt.",
     "content": "Die Testgruppe meldet Auffaelligkeiten direkt ueber ein kurzes Formular in der App. Erst wenn ueber mehrere Tage keine schwerwiegenden Rueckmeldungen eingehen, wird die Version fuer eine groessere Gruppe freigegeben. Der Ablauf ist bewusst schlank gehalten, weil es sich um eine private Lern-App handelt."},
    {"abteilung": "openlehr-privat", "slug": "openlehr-fehlerprotokoll-auswertung",
     "title": "Auswertung des Fehlerprotokolls", "summary": "Das Fehlerprotokoll der openlehr-App wird regelmaessig durchsucht, um wiederkehrende Abstuerze fruehzeitig zu erkennen.",
     "content": "Haeufungen an derselben Stelle im Protokoll deuten meist auf ein grundsaetzliches statt ein einmaliges Problem hin. Auffaelligkeiten werden nach Haeufigkeit sortiert und in kleinen Schritten abgearbeitet. Seltene Einzelfaelle werden vorerst nur beobachtet."},
    {"abteilung": "openlehr-privat", "slug": "openlehr-offline-modus-pruefung",
     "title": "Pruefung des Offline-Modus", "summary": "Der Offline-Modus der openlehr-App wird regelmaessig gepruft, damit Lerninhalte auch ohne Internetverbindung nutzbar bleiben.",
     "content": "Getestet wird unter anderem, was passiert, wenn die Verbindung mitten in einer Uebung abbricht und spaeter wiederkehrt. Ziel ist, dass keine Eingaben verlorengehen und der Fortschritt korrekt weitergefuehrt wird. Auffaelligkeiten werden im Fehlerprotokoll separat markiert."},
    {"abteilung": "openlehr-privat", "slug": "openlehr-startzeit-optimierung",
     "title": "Optimierung der Startzeit", "summary": "Die Startzeit der openlehr-App wird gemessen und schrittweise verbessert, damit Nutzer nicht unnoetig lange auf den ersten Bildschirm warten.",
     "content": "Gemessen wird die Zeit vom Antippen des App-Symbols bis zur Anzeige des ersten nutzbaren Inhalts. Verzoegerungen werden meist durch unnoetig fruehes Laden von Inhalten verursacht, die erst spaeter gebraucht werden. Verbesserungen werden vor der naechsten Auslieferung erneut gemessen."},
    {"abteilung": "openlehr-privat", "slug": "openlehr-barrierefreiheit-kontrast",
     "title": "Kontrastpruefung fuer Barrierefreiheit", "summary": "Die Farbkontraste in der openlehr-App werden gegen die uebliche Mindestanforderung fuer Fliesstext und Bedienelemente geprueft.",
     "content": "Die Pruefung erfolgt anhand der hinterlegten Farbwerte, nicht nach Augenmass. Faellt ein Element unter den Mindestwert, wird die Farbe im zentralen Farbschema angepasst, nicht nur an der einzelnen Stelle. So bleibt die Aenderung an allen Stellen wirksam, an denen die Farbe verwendet wird."},
    {"abteilung": "openlehr-privat", "slug": "openlehr-nutzerfeedback-sichtung",
     "title": "Sichtung von Nutzerfeedback", "summary": "Rueckmeldungen aus der openlehr-App werden gesammelt gesichtet, bevor daraus neue Aufgaben fuer die naechste Version entstehen.",
     "content": "Die Sichtung unterscheidet zwischen Fehlermeldungen, Verstaendlichkeitsproblemen und Wuenschen nach neuen Inhalten. Haeufig genannte Punkte werden bevorzugt eingeplant, Einzelmeinungen zunaechst zurueckgestellt. Die Sichtung findet in ruhigen Abstaenden statt, nicht nach jeder einzelnen Meldung."},
]

FUELL_LEHREN: list[dict] = [
    # verbrauchsabrechnung
    {"abteilung": "verbrauchsabrechnung", "typ": "pattern", "severity": "medium",
     "description": "Stapelweise Verarbeitung im Rechnungslauf begrenzt den Schaden eines Abbruchs auf einen Teilbereich.",
     "root_cause": "Ein einzelner grosser Lauf ohne Zwischenschritte fuehrt bei Abbruch zu vollstaendigem Neustart.",
     "prevention": "Verarbeitung in feste, wiederholbare Stapel aufteilen und je Stapel einen Wiederanlaufpunkt vorsehen."},
    {"abteilung": "verbrauchsabrechnung", "typ": "antipattern", "severity": "medium",
     "description": "Ein Prognosemodell ohne jaehrliche Neukalibrierung veraltet unbemerkt gegenueber dem tatsaechlichen Verbrauch.",
     "root_cause": "Die Kalibrierung wurde einmalig eingerichtet und danach nicht mehr routinemaessig wiederholt.",
     "prevention": "Feste jaehrliche Kalibrierungstermine im Kalender verankern, nicht dem Zufall ueberlassen."},
    {"abteilung": "verbrauchsabrechnung", "typ": "error", "severity": "low",
     "description": "Die Schaltjahr-Korrektur der Abrechnungsperiode wurde in einem Jahr vergessen und fiel erst bei der Jahresuebersicht auf.",
     "root_cause": "Die Korrektur war nicht Teil eines automatisierten Ablaufs, sondern ein manueller Jahreshinweis.",
     "prevention": "Die Tageszahl der Periode automatisch aus dem Kalenderjahr ableiten statt manuell zu pflegen."},
    {"abteilung": "verbrauchsabrechnung", "typ": "insight", "severity": "low",
     "description": "Plausibilitaetsregeln fangen mehr Faelle, wenn sie den Verlauf mehrerer Perioden statt nur des Vorjahres vergleichen.",
     "root_cause": "Ein Vergleich mit nur einer Vorperiode uebersieht schleichende, aber stetige Verbrauchsaenderungen.",
     "prevention": "Regel auf den Verlauf mehrerer Perioden auslegen, nicht nur auf einen einzelnen Vorjahreswert."},
    {"abteilung": "verbrauchsabrechnung", "typ": "pattern", "severity": "medium",
     "description": "Ein festes Freigabefenster fuer Tarifwechsel verhindert doppelte Buchungen im Abrechnungssystem.",
     "root_cause": "Wechsel ausserhalb eines geordneten Zeitpunkts konnten sich mit laufenden Buchungen ueberschneiden.",
     "prevention": "Wechsel nur innerhalb definierter Fenster technisch scharfstellen, ausserhalb in eine Warteliste einreihen."},
    {"abteilung": "verbrauchsabrechnung", "typ": "insight", "severity": "low",
     "description": "Ein taeglicher Vollstaendigkeits-Check der Lastgangdaten deckt fehlende Uebertragungsbloecke frueher auf als ein monatlicher Abgleich.",
     "root_cause": "Fehlende Bloecke fielen bislang erst bei der naechsten grossen Auswertung auf.",
     "prevention": "Vollstaendigkeit taeglich statt monatlich pruefen und Abweichungen sofort zurueckmelden."},
    # netzbetrieb
    {"abteilung": "netzbetrieb", "typ": "pattern", "severity": "medium",
     "description": "Ein gemeinsamer Baustellenkalender mit anderen Leitungstraegern reduziert doppelte Sperrungen im selben Strassenzug.",
     "root_cause": "Getrennte Planungen ohne Abgleich fuehrten zu mehrfachen Grabungen an derselben Stelle.",
     "prevention": "Vorhaben vor Ausschreibung gegen einen gemeinsamen Kalender pruefen und Ueberschneidungen zusammenlegen."},
    {"abteilung": "netzbetrieb", "typ": "error", "severity": "high",
     "description": "Eine neue Ladesaeule wurde ohne vorherige Lastsimulation angeschlossen und fuehrte bei Gleichzeitigkeit zu einer Spannungsabweichung.",
     "root_cause": "Die Pruefung der Gleichzeitigkeit mehrerer Ladevorgaenge war kein verpflichtender Schritt vor der Freigabe.",
     "prevention": "Lastsimulation als verpflichtenden Schritt vor jede Inbetriebnahme einer Ladesaeule stellen."},
    {"abteilung": "netzbetrieb", "typ": "insight", "severity": "medium",
     "description": "Eine automatisierte Priorisierung nach Anzahl betroffener Anschluesse bringt den Bereitschaftsdienst schneller zur richtigen Stoerung.",
     "root_cause": "Manuelle Priorisierung nach Eingangsreihenfolge liess grossflaechige Ausfaelle zu spaet erkennen.",
     "prevention": "Priorisierung automatisiert an der Anzahl betroffener Anschluesse ausrichten, nicht an der Meldereihenfolge."},
    {"abteilung": "netzbetrieb", "typ": "pattern", "severity": "low",
     "description": "Eine vorab abgestimmte Liste kritischer Zufahrten macht den Winterdienst fuer Netzanlagen planbar statt reaktiv.",
     "root_cause": "Ohne vorab abgestimmte Liste wurde bei Schneefall situativ entschieden, was zu spaeten Raeumungen fuehrte.",
     "prevention": "Kritische Standorte vor der Saison mit dem Raeumdienst abstimmen und die Liste bei Bedarf taeglich anpassen."},
    {"abteilung": "netzbetrieb", "typ": "antipattern", "severity": "low",
     "description": "Fuhrpark-Buchungen ohne zentrale Uebersicht fuehrten wiederholt zu doppelt eingeplanten Fahrzeugen.",
     "root_cause": "Jedes Team pflegte eine eigene Liste statt eines gemeinsamen Buchungssystems.",
     "prevention": "Ein zentrales Buchungssystem fuer alle Teams verbindlich machen statt paralleler Listen."},
    # kundenservice
    {"abteilung": "kundenservice", "typ": "insight", "severity": "medium",
     "description": "Ein Rueckrufangebot bei hohem Anrufaufkommen senkt die gefuehlte Wartezeit staerker als eine laengere Warteschleife.",
     "root_cause": "Anrufer legten bei langer Warteschleife haeufiger auf und riefen mehrfach erneut an.",
     "prevention": "Bei Ueberlast einen Rueckruf anbieten statt die Warteschleife unbegrenzt zu verlaengern."},
    {"abteilung": "kundenservice", "typ": "pattern", "severity": "low",
     "description": "Kuerzere Terminfenster fuer Vor-Ort-Termine erhoehen die Zufriedenheit, auch wenn dadurch mehr Fenster geplant werden muessen.",
     "root_cause": "Breite Vier-Stunden-Fenster zwangen Kunden zu langem Warten zuhause.",
     "prevention": "Fensterbreite an der Kundenrueckmeldung ausrichten statt an der einfacheren Planung fuer das Team."},
    {"abteilung": "kundenservice", "typ": "insight", "severity": "low",
     "description": "Eine Kategorisierung von Beschwerden bei Eingang macht wiederkehrende Ursachen erst im Monatsreport sichtbar.",
     "root_cause": "Unkategorisierte Freitext-Beschwerden liessen sich nur mit hohem Aufwand nachtraeglich auswerten.",
     "prevention": "Kategorie bereits beim Eingang der Beschwerde erfassen, nicht erst bei der spaeteren Auswertung."},
    {"abteilung": "kundenservice", "typ": "antipattern", "severity": "medium",
     "description": "Ein zu unuebersichtliches Kundenportal trieb einfache Anliegen zurueck in die Telefonwarteschlange.",
     "root_cause": "Menuepunkte im Portal folgten der internen Systemstruktur statt der Nutzersicht.",
     "prevention": "Menuepunkte nach haeufigen Kundenanliegen ordnen und regelmaessig gegen echte Nutzung pruefen."},
    {"abteilung": "kundenservice", "typ": "insight", "severity": "low",
     "description": "Eine kurze Nachbefragung nach dem Vor-Ort-Termin deckt Probleme im Ablauf frueher auf als eine spaetere Jahresumfrage.",
     "root_cause": "Ohne zeitnahe Rueckmeldung blieben kleinere Ablaufprobleme lange unbemerkt.",
     "prevention": "Kurze Nachbefragung direkt nach dem Termin einholen statt nur einmal jaehrlich zu befragen."},
    # personal
    {"abteilung": "personal", "typ": "pattern", "severity": "medium",
     "description": "Ein dokumentiertes Uebergabeprotokoll zwischen Schichten verhindert, dass offene Vorgaenge zwischen zwei Diensten verlorengehen.",
     "root_cause": "Muendliche Uebergaben ohne Protokoll gingen bei kurzfristigem Schichtwechsel manchmal unter.",
     "prevention": "Uebergabe grundsaetzlich schriftlich im gemeinsamen Protokoll festhalten, nicht nur muendlich weitergeben."},
    {"abteilung": "personal", "typ": "insight", "severity": "low",
     "description": "Eine automatische Erinnerung vor Ablauf der Schulungsfrist senkt die Zahl verpasster Pflichtschulungen.",
     "root_cause": "Ohne Erinnerung wurde der Fristablauf oft erst durch die Fuehrungskraft bemerkt.",
     "prevention": "Erinnerung rechtzeitig vor Fristablauf automatisiert an die betroffene Person schicken."},
    {"abteilung": "personal", "typ": "antipattern", "severity": "medium",
     "description": "Ein Turnus fuer den Bereitschaftsdienst ohne Beruecksichtigung vorheriger Wochen belastete einzelne Kollegen ungleich staerker.",
     "root_cause": "Die Einteilung erfolgte nach Verfuegbarkeit statt nach bisheriger Bereitschaftshaeufigkeit.",
     "prevention": "Rotation an der Historie vorheriger Bereitschaftswochen ausrichten, nicht nur an aktueller Verfuegbarkeit."},
    {"abteilung": "personal", "typ": "insight", "severity": "low",
     "description": "Ein strukturierter Einarbeitungsplan mit wechselnden Stationen vermittelt Zusammenhaenge zwischen Abteilungen besser als eine Einweisung an einem Platz.",
     "root_cause": "Neue Mitarbeitende sahen bei einer einzelnen Station nicht, wie ihre Arbeit mit anderen Teams zusammenhaengt.",
     "prevention": "Einarbeitung ueber mehrere Stationen mit kurzem Feedback am Ende jeder Station gestalten."},
    {"abteilung": "personal", "typ": "pattern", "severity": "low",
     "description": "Ein kurzes Protokoll nach jeder Teamsitzung haelt Beschluesse auch fuer abwesende Kollegen nachvollziehbar fest.",
     "root_cause": "Ohne Protokoll gingen Beschluesse aus Sitzungen bei Abwesenheit einzelner Kollegen verloren.",
     "prevention": "Protokollpflicht fuer jede regelmaessige Sitzung einfuehren und zeitnah ablegen."},
    # openlehr-privat
    {"abteilung": "openlehr-privat", "typ": "insight", "severity": "medium",
     "description": "Eine Auswertung der Testabdeckung nach Modul zeigt gezielter, wo als naechstes ein Test fehlt, als ein pauschaler Gesamtwert.",
     "root_cause": "Ein einzelner Gesamtprozentwert verdeckte, dass einzelne neue Module fast ungeprueft blieben.",
     "prevention": "Testabdeckung je Modul auswerten und neue Bildschirme bevorzugt mit einem Test versehen."},
    {"abteilung": "openlehr-privat", "typ": "antipattern", "severity": "low",
     "description": "Uneinheitliche Beschriftung gleicher Funktionen auf verschiedenen Bildschirmen verwirrte Nutzer der openlehr-App.",
     "root_cause": "Neue Bildschirme entstanden ohne Blick auf bereits verwendete Begriffe im Rest der App.",
     "prevention": "Vor dem Anlegen eines neuen Bildschirms bestehende Begriffe nachschlagen und wiederverwenden."},
    {"abteilung": "openlehr-privat", "typ": "pattern", "severity": "medium",
     "description": "Eine schrittweise Auslieferung ueber eine kleine Testgruppe faengt Probleme ab, bevor sie eine groessere Gruppe erreichen.",
     "root_cause": "Eine direkte Auslieferung an alle Nutzenden liess grosse Probleme erst spaet auffallen.",
     "prevention": "Neue Versionen zunaechst an eine kleine Gruppe ausliefern und erst nach ruhiger Frist breiter freigeben."},
    {"abteilung": "openlehr-privat", "typ": "insight", "severity": "low",
     "description": "Haeufungen an derselben Stelle im Fehlerprotokoll sind ein zuverlaessigerer Hinweis auf ein grundsaetzliches Problem als Einzelmeldungen.",
     "root_cause": "Einzelne seltene Meldungen wurden frueher genauso behandelt wie haeufig wiederkehrende.",
     "prevention": "Fehlerprotokoll nach Haeufigkeit sortiert auswerten und Haeufungen bevorzugt bearbeiten."},
    {"abteilung": "openlehr-privat", "typ": "pattern", "severity": "medium",
     "description": "Kontrastwerte aus dem zentralen Farbschema zu berechnen statt frei zu waehlen, haelt alle Stellen der App gleichzeitig konform.",
     "root_cause": "Einzeln gewaehlte Farben an einzelnen Stellen fielen bei Pruefung unter den Mindestkontrast.",
     "prevention": "Farben nur im zentralen Farbschema aendern, nie an einzelnen Bildschirmen isoliert anpassen."},
]
