#!/usr/bin/env bash
# VERSIONIERTE FASSUNG. Installieren:
#   cp haken/git/commit-msg .git/hooks/commit-msg && chmod +x .git/hooks/commit-msg
#
# Haelt einen Commit an, der eine BEHEBUNG behauptet und weder eine Testdatei
# noch einen Beleg im Text nennt. Gemessen am 2026-08-20: 92 von 1 193 Commits
# seit dem 2026-08-01 waeren betroffen gewesen (7,7 %).
#
# Abschaltbar fuer einen einzelnen Commit: BRAINLEHR_ROTPROBE=aus git commit ...
exec python3 /Volumes/daten/Begod2026/brainlehr/melder/rotprobe.py --commit-msg "$1"
